version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpassword123
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP Browser
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/strongpassword123
    volumes:
      - neo4j_data:/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  neo4j_data:
  ollama_data: